version: 0.2
phases:
  pre_build:
    commands:
      # using a time variable to output at the end to aid where builds may take along time.
      - time="Start - $(date +%r)"
  build:
    commands:
      - phase=test
      - echo testing
