#
######################################################################
version: 0.2
env:
  variables:
    GITHUB_USERNAME: 'va-bot'
    # These are the test make targets.
    TESTS: 'images lint security unit e2e accessibility visual'
    # These are the build environments
    ENVIRONMENTS: 'dev staging production'
    # Bucket for archiving deployments
    S3_ARCHIVE_BUCKET: 'developer-portal-builds-s3-upload'
    # Bucket for uploading visual regression failures.
    S3_VISUAL_BUCKET: 'developer-portal-screenshots'
    # Bucket for uploading build failure artifacts
    S3_ERROR_BUCKET: 'developer-portal-ci-error-artifacts'
    # Bucket for uploading PR deploy previews.
    S3_REVIEW_BUCKET: 'review-developer-va-gov'
    ## move to paramstore
    PREVIEW_SENTRY_DSN: 'http://dc7d5ebec20e474c80f8150c399d2955@sentry.vfs.va.gov/26'
    # Setting REPO
    REPO: 'department-of-veterans-affairs/developer-portal'
    # Running the container as root.
    UNAME: root
    GNAME: root
  parameter-store:
    GITHUB_TOKEN: '/dvp/devops/va_bot_github_token'
    DOCKER_USERNAME: '/dvp/devops/DOCKER_USERNAME'
    DOCKER_PASSWORD: '/dvp/devops/DOCKER_PASSWORD'
    # This webhook currently targets DSVA workspace #lighthous-deploys channel
    #
phases:
  install:
    commands:
      # There is considerable slow down in the provisioning phase when using Amazon provided images.
      # Therefore we use our own Alpine based image. In order to activate the Docker Daemon these lines are needed.
      - /usr/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - |
        for env in ${ENVIRONMENTS}; do
        # Login to Docker Hub prior to pulling Dockerfile's base image node:12. This prevents rate limiting from Docker Hub.
      - echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
      - make build
  build:
    commands:
      - aws s3 sync --no-progress --acl public-read build/ s3://${S3_REVIEW_BUCKET}/${S3_BRANCH}/${COMMIT_HASH}/
      - |
        links=""
        for env in ${ENVIRONMENTS}; do
          links="${links} - [${env}](https://s3-us-gov-west-1.amazonaws.com/${S3_REVIEW_BUCKET}/${S3_BRANCH}/${COMMIT_HASH}/${env}/index.html) <br>"
        done
      - comment="These changes have been deployed to an S3 bucket. A build for each environment is available: <br><br> ${links} <br> Due to S3 website hosting limitations in govcloud you need to first navigate to index.html explicitly."
      - prcomment.sh ${REPO} ${PR_NUM} "${comment:-"CI Job has finished successfully."}"
